package com.wisdom.entity;

import java.io.Serializable;

public class HotelInfoImg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info_img.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info_img.img_name
     *
     * @mbggenerated
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info_img.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info_img.img_content
     *
     * @mbggenerated
     */
    private String imgContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info_img.hotel_info_id
     *
     * @mbggenerated
     */
    private Integer hotelInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info_img.id
     *
     * @return the value of hotel_info_img.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info_img.id
     *
     * @param id the value for hotel_info_img.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info_img.img_name
     *
     * @return the value of hotel_info_img.img_name
     *
     * @mbggenerated
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info_img.img_name
     *
     * @param imgName the value for hotel_info_img.img_name
     *
     * @mbggenerated
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info_img.img_url
     *
     * @return the value of hotel_info_img.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info_img.img_url
     *
     * @param imgUrl the value for hotel_info_img.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info_img.img_content
     *
     * @return the value of hotel_info_img.img_content
     *
     * @mbggenerated
     */
    public String getImgContent() {
        return imgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info_img.img_content
     *
     * @param imgContent the value for hotel_info_img.img_content
     *
     * @mbggenerated
     */
    public void setImgContent(String imgContent) {
        this.imgContent = imgContent == null ? null : imgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info_img.hotel_info_id
     *
     * @return the value of hotel_info_img.hotel_info_id
     *
     * @mbggenerated
     */
    public Integer getHotelInfoId() {
        return hotelInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info_img.hotel_info_id
     *
     * @param hotelInfoId the value for hotel_info_img.hotel_info_id
     *
     * @mbggenerated
     */
    public void setHotelInfoId(Integer hotelInfoId) {
        this.hotelInfoId = hotelInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", imgName=").append(imgName);
        sb.append(", imgUrl=").append(imgUrl);
        sb.append(", imgContent=").append(imgContent);
        sb.append(", hotelInfoId=").append(hotelInfoId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}