package com.wisdom.entity;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;


public class HotelType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoteltype.id
     *
     * @mbggenerated
     */
    @ApiModelProperty("酒店类型id")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoteltype.typeCode
     *
     * @mbggenerated
     */
    @ApiModelProperty("酒店类型编码")
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoteltype.typeName
     *
     * @mbggenerated
     */
    @ApiModelProperty("酒店类型名称")
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoteltype.remark
     *
     * @mbggenerated
     */
    @ApiModelProperty("酒店类型备注")
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoteltype.id
     *
     * @return the value of hoteltype.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoteltype.id
     *
     * @param id the value for hoteltype.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoteltype.typeCode
     *
     * @return the value of hoteltype.typeCode
     *
     * @mbggenerated
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoteltype.typeCode
     *
     * @param typecode the value for hoteltype.typeCode
     *
     * @mbggenerated
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoteltype.typeName
     *
     * @return the value of hoteltype.typeName
     *
     * @mbggenerated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoteltype.typeName
     *
     * @param typename the value for hoteltype.typeName
     *
     * @mbggenerated
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoteltype.remark
     *
     * @return the value of hoteltype.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoteltype.remark
     *
     * @param remark the value for hoteltype.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", typecode=").append(typecode);
        sb.append(", typename=").append(typename);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}