package com.wisdom.mapper;


import com.wisdom.entity.HotelInfo;
import com.wisdom.entity.HotelInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface HotelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    int countByExample(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    int deleteByExample(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    int insert(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    int insertSelective(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    List<HotelInfo> selectByExample(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    HotelInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HotelInfo record, @Param("example") HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HotelInfo record, @Param("example") HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotelInfo record);
}