package com.wisdom.mapper;

import com.wisdom.entity.HotelType;
import com.wisdom.entity.HotelTypeExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface HotelTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    int countByExample(HotelTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    int deleteByExample(HotelTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    int insert(HotelType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    int insertSelective(HotelType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    List<HotelType> selectByExample(HotelTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    HotelType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HotelType record, @Param("example") HotelTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HotelType record, @Param("example") HotelTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotelType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoteltype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotelType record);
}