package com.wisdom.mapper;


import com.wisdom.entity.HotelOrder;
import com.wisdom.entity.HotelOrderExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface HotelOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    int countByExample(HotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    int deleteByExample(HotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    int insert(HotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    int insertSelective(HotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    List<HotelOrder> selectByExample(HotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    HotelOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HotelOrder record, @Param("example") HotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HotelOrder record, @Param("example") HotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotelOrder record);
}