package com.wisdom.mapper;

import com.wisdom.entity.HotelInfoImg;
import com.wisdom.entity.HotelInfoImgExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface HotelInfoImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    int countByExample(HotelInfoImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    int deleteByExample(HotelInfoImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    int insert(HotelInfoImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    int insertSelective(HotelInfoImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    List<HotelInfoImg> selectByExample(HotelInfoImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    HotelInfoImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HotelInfoImg record, @Param("example") HotelInfoImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HotelInfoImg record, @Param("example") HotelInfoImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotelInfoImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotelInfoImg record);
}